### ISSUE TITLE
Calculating theta

### ISSUE THREAD

**Issue by skreckli** [ncsu-geoforall-lab/geospatial-nc-wwpatrn#1]
Running 'compute_flow_columns' on CarySouthsewer network and getting following error:
```
grass.exceptions.CalledModuleError: Module run None
v.db.pyupdate map=cary_grav_carySouth@PERMANENT column=theta
expression=2 * math.acos((radius_ft - liquid_height) /
radius_ft) ended with error
Process ended with non-zero return code 1. See errors in the
(error) output.
```
The theta column on the attribute table is empty and I couldn't get it to field calculate by entering the equation:
2 * math.acos((radius_ft - liquid_height) /radius_ft)

**Comment by wenzeslaus** [comment]
I originally thought this is more complicated, but perhaps it isn't. Do you have v.db.pyupdate installed? I updated the readme to highlight the need for it. (I just mentioned in an email before, but it was not yet available in addons at that time.)

**Comment by skreckli** [comment]
I did install it.  I verified that it is working in GRASS by typing 'v.db.pyupdate' in the console and the GUI pops up.  FYI-I had trouble in ArcPro running the arccosine function using the python3 command 'math.acos' and ended up using excel to calculate this part of the equation.

**Comment by wenzeslaus** [comment]
Well, that is strange. Do you see any errors above the traceback, i.e., above the word `Traceback`?

In the example below the part `ERROR: ...module 'math' has no attribute 'xacos'` would be the most relevant now.

```
ERROR: Evaluation of expression <2 * math.xacos((radi...> where
       radius_ft=0.333333333333333, liquid_height=0.166666666666667 failed
       with: module 'math' has no attribute 'xacos'
Traceback (most recent call last):
  File "./geospatial-nc-wwpatrn/compute_flow_columns.py", line 80, in <module>
    sys.exit(main())
  File "./geospatial-nc-wwpatrn/compute_flow_columns.py", line 67, in main
    add_float_column_py(
  File "./geospatial-nc-wwpatrn/compute_flow_columns.py", line 48, in add_float_column_py
    gs.run_command("v.db.pyupdate", map=vector, column=name, expression=expression)
  File "/home/vpetras/Projects/grass/code/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 501, in run_command
    return handle_errors(returncode, result=None, args=args, kwargs=kwargs)
  File "/home/vpetras/Projects/grass/code/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run v.db.pyupdate v.db.pyupdate map=lines column=theta expression=2 * math.xacos((radius_ft - liquid_height) / radius_ft) ended with error
Process ended with non-zero return code 1. See errors in the (error) output.
```

**Comment by skreckli** [comment]
For sure!  I haven't tried to run this recently so I just emailed you a link to a folder on my google drive so you can download the data and try out the script on the cary_grav_carySouth sewer network.  Maybe it will work for you and it was just user error on my part (which is entirely possible!)

**Comment by skreckli** [comment]
I finally found some time to try this again.  Here is the error above the traceback:
ERROR: v.db.select: Sorry, <j> is not a valid flag

**Comment by wenzeslaus** [comment]
Thanks for looking into this. I see. I forgot how new the JSON feature I'm using in v.db.select is. You either need install the daily build (aka 7.9 right now) or wait for me to make this compatible with 7.8.

**Comment by wenzeslaus** [comment]
v7.8 compatibility added in https://github.com/OSGeo/grass-addons/pull/356 Install new version with:

```
g.extension v.db.pyupdate
```

Closing. Let me know if there are further issues.
